package server.gamelog;

public enum EGamelog {
	  GAMELOG_BEGIN,
	  GAMELOG_END,
	  GAMELOG_JUDGE,
	  GAMELOG_MAP,
	  GAMELOG_PLAYER,
	  GAMELOG_TEAM,
	  GAMELOG_WONDER,
	  GAMELOG_FOUNDCITY,
	  GAMELOG_LOSECITY,
	  GAMELOG_DISBANDCITY,
	  GAMELOG_TECH,
	  GAMELOG_EMBASSY,
	  GAMELOG_GOVERNMENT,
	  GAMELOG_REVOLT,
	  GAMELOG_GENO,
	  GAMELOG_TREATY,
	  GAMELOG_DIPLSTATE,
	  GAMELOG_STATUS,
	  GAMELOG_FULL,		/* placeholder */
	  GAMELOG_INFO,
	  GAMELOG_UNITLOSS,
	  GAMELOG_UNITGAMELOSS,
	  GAMELOG_BUILD,
	  GAMELOG_RATECHANGE,
	  GAMELOG_EVERYTHING,
	  GAMELOG_DEBUG

}
