package common.effects;
/* Type of effects. (Used in effect.type field)
 * These must correspond to effect_type_names[] in effects.c. */
public enum effect_type {
  EFT_TECH_PARASITE,
  EFT_AIRLIFT,
  EFT_ANY_GOVERNMENT,
  EFT_CAPITAL_CITY,
  EFT_CORRUPT_PCT,
  EFT_WASTE_PCT,
  EFT_ENABLE_NUKE,
  EFT_ENABLE_SPACE,
  EFT_FOOD_ADD_TILE,
  /* TODO: EFT_FOOD_BONUS, */
  /* TODO: EFT_FOOD_PCT, */
  EFT_FOOD_INC_TILE,
  EFT_FOOD_PER_TILE,
  EFT_FORCE_CONTENT,
  /* TODO: EFT_FORCE_CONTENT_PCT, */
  EFT_GIVE_IMM_TECH,
  EFT_GROWTH_FOOD,
  EFT_HAVE_EMBASSIES,
  EFT_LUXURY_BONUS,
  /* TODO: EFT_LUXURY_PCT, */
  EFT_MAKE_CONTENT,
  EFT_MAKE_CONTENT_MIL,
  EFT_MAKE_CONTENT_MIL_PER,
  /* TODO: EFT_MAKE_CONTENT_PCT, */
  EFT_MAKE_HAPPY,
  EFT_NO_ANARCHY,
  EFT_NO_SINK_DEEP,
  EFT_NUKE_PROOF,
  /* TODO: EFT_POLLU_ADJ, */
  /* TODO: EFT_POLLU_PCT, */
  /* TODO: EFT_POLLU_POP_ADJ, */
  EFT_POLLU_POP_PCT,
  /* TODO: EFT_POLLU_PROD_ADJ, */
  EFT_POLLU_PROD_PCT,
  EFT_PROD_ADD_TILE,
  EFT_PROD_BONUS,
  /* TODO: EFT_PROD_PCT, */
  EFT_PROD_INC_TILE,
  EFT_PROD_PER_TILE,
  EFT_PROD_TO_GOLD,
  EFT_REVEAL_CITIES,
  EFT_REVEAL_MAP,
  /* TODO: EFT_INCITE_DIST_ADJ, */
  EFT_INCITE_DIST_PCT,
  EFT_SCIENCE_BONUS,
  /* TODO: EFT_SCIENCE_PCT, */
  EFT_SIZE_ADJ,
  EFT_SIZE_UNLIMIT,
  EFT_SS_STRUCTURAL,
  EFT_SS_COMPONENT,
  EFT_SS_MODULE,
  EFT_SPY_RESISTANT,
  EFT_TAX_BONUS,
  /* TODO: EFT_TAX_PCT, */
  EFT_TRADE_ADD_TILE,
  /* TODO: EFT_TRADE_BONUS, */
  /* TODO: EFT_TRADE_PCT, */
  EFT_TRADE_INC_TILE,
  EFT_TRADE_PER_TILE,
  EFT_SEA_MOVE,
  EFT_UNIT_NO_LOSE_POP,
  EFT_UNIT_RECOVER,
  EFT_UPGRADE_UNIT,
  EFT_UPKEEP_FREE,
  EFT_NO_UNHAPPY,
  EFT_LAND_VETERAN,
  EFT_SEA_VETERAN,
  EFT_AIR_VETERAN,
  EFT_LAND_VET_COMBAT,
  /* TODO: EFT_SEA_VET_COMBAT, */
  /* TODO: EFT_AIR_VET_COMBAT, */
  EFT_LAND_REGEN,
  EFT_SEA_REGEN,
  EFT_AIR_REGEN,
  EFT_LAND_DEFEND,
  EFT_SEA_DEFEND,
  EFT_AIR_DEFEND,
  EFT_MISSILE_DEFEND,
  EFT_NO_INCITE,
  EFT_REGEN_REPUTATION,
  EFT_GAIN_AI_LOVE,
  EFT_LAST	/* keep this last */
};
